package com.houseofbeauty.service.dataupload.import_common;

import com.houseofbeauty.service.common.TableAccessService;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceUtils;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Savepoint;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Validates and (candidate rows only) inserts one chunk's worth of rows — the row-level engine shared
 * by both {@link ImportValidationRunner} (parallel, always rolled back) and
 * {@link ImportAtomicCommitRunner} (sequential, one transaction for the whole file). Assumes it's
 * already running inside an active transaction/connection; the caller owns transaction boundaries and
 * IDENTITY_INSERT toggling. Any exception here is left to propagate to the caller rather than being
 * swallowed, so a real system failure correctly fails the whole enclosing transaction instead of being
 * silently absorbed into a per-row error.
 *
 * <p>Every row that would be marked INVALID or DUPLICATE first goes through
 * {@link #reserveInvalidSlot}: once the shared budget (see {@link ImportLimits#MAX_INVALID_ROWS}) is
 * exhausted, remaining rows in this chunk (and, via the shared stop signal, in every other chunk) are
 * simply left unprocessed rather than evaluated and discarded — what keeps a 1,000,000-row file from
 * being fully scanned just to throw away everything past row 10.
 */
class ImportChunkRowProcessor {

    private final TableAccessService tableAccessService;
    private final JdbcTemplate jdbcTemplate;

    ImportChunkRowProcessor(TableAccessService tableAccessService, JdbcTemplate jdbcTemplate) {
        this.tableAccessService = tableAccessService;
        this.jdbcTemplate = jdbcTemplate;
    }

    ImportProcessingService.ChunkOutcome processChunkCore(ImportProcessingService.RunContext ctx,
                                                           ImportProcessingService.ValidationState state,
                                                           List<List<String>> chunk, int startingRowNumber,
                                                           boolean simulateIdentityForDryRun) {
        int[] inserted = {0};
        int[] duplicates = {0};
        int[] errors = {0};
        ImportProcessingService.RowResult[] resultsByPosition =
                new ImportProcessingService.RowResult[chunk.size()];

        // Looked up from the table's own identity columns, not the file's headers — an
        // auto-generated identity column is, by definition, usually absent from the file's own
        // header row, so searching the headers here would silently find nothing.
        String identityColumnForDryRun = simulateIdentityForDryRun
                ? ctx.identityColumns().stream()
                        .filter(c -> ctx.autoGeneratedColumns().contains(c.toLowerCase(Locale.ROOT)))
                        .findFirst().orElse(null)
                : null;

        List<Map<String, Object>> rowValuesByPosition = new ArrayList<>(chunk.size());
        List<String> effectiveColumns = null;
        for (int i = 0; i < chunk.size(); i++) {
            List<String> rawRow = chunk.get(i);
            Map<String, Object> rowValues = new LinkedHashMap<>();
            for (int c = 0; c < ctx.headers().size() && c < rawRow.size(); c++) {
                String header = ctx.headers().get(c);
                if (ctx.autoGeneratedColumns().contains(header.toLowerCase(Locale.ROOT))) {
                    continue;
                }
                String value = rawRow.get(c);
                if (value != null && !value.isEmpty() && ctx.dateColumnsLower().contains(header.toLowerCase(Locale.ROOT))) {
                    value = ImportValueNormalizer.normalizeDateText(value);
                }
                rowValues.put(header, value == null || value.isEmpty() ? null : value);
            }
            rowValuesByPosition.add(rowValues);
            if (effectiveColumns == null) {
                effectiveColumns = new ArrayList<>(rowValues.keySet());
            }
        }

        // Insert-only view of the same rows: identical to rowValuesByPosition except, during a dry
        // run, it also carries a throwaway negative value for the auto-generated identity column so
        // the real, rolled-back INSERT never touches the actual identity sequence (see
        // ImportValidationRunner's javadoc / IDENTITY_INSERT comment history).
        List<Map<String, Object>> insertValuesByPosition = rowValuesByPosition;
        List<String> insertColumns = effectiveColumns;
        if (identityColumnForDryRun != null) {
            insertColumns = new ArrayList<>(effectiveColumns);
            insertColumns.add(identityColumnForDryRun);
            List<Map<String, Object>> augmented = new ArrayList<>(rowValuesByPosition.size());
            for (int i = 0; i < rowValuesByPosition.size(); i++) {
                Map<String, Object> augmentedRow = new LinkedHashMap<>(rowValuesByPosition.get(i));
                augmentedRow.put(identityColumnForDryRun, -(startingRowNumber + i + 1));
                augmented.add(augmentedRow);
            }
            insertValuesByPosition = augmented;
        }

        if (!ctx.appManagedPkBaseValues().isEmpty()) {
            List<String> withAppManagedPk = new ArrayList<>(insertColumns);
            withAppManagedPk.addAll(ctx.appManagedPkBaseValues().keySet());
            List<Map<String, Object>> augmented = new ArrayList<>(insertValuesByPosition.size());
            for (int i = 0; i < insertValuesByPosition.size(); i++) {
                Map<String, Object> augmentedRow = new LinkedHashMap<>(insertValuesByPosition.get(i));
                for (Map.Entry<String, Long> entry : ctx.appManagedPkBaseValues().entrySet()) {
                    augmentedRow.put(entry.getKey(), entry.getValue() + startingRowNumber + i);
                }
                augmented.add(augmentedRow);
            }
            insertColumns = withAppManagedPk;
            insertValuesByPosition = augmented;
        }

        // Precision-risk pass — flags cells whose source value may have already lost precision
        // before this code ever ran (see isRiskyNumericCell/isRiskyScientificNotation in
        // ImportUploadFileParser).
        for (int i = 0; i < chunk.size(); i++) {
            if (state.shouldStop()) {
                return finishChunk(resultsByPosition, inserted, duplicates, errors);
            }
            Set<String> riskyColumns = ctx.precisionRiskCells().get(startingRowNumber + i);
            if (riskyColumns == null || riskyColumns.isEmpty()) {
                continue;
            }
            if (!reserveInvalidSlot(state)) {
                return finishChunk(resultsByPosition, inserted, duplicates, errors);
            }
            String column = riskyColumns.iterator().next();
            int rowNumber = startingRowNumber + i + 1;
            resultsByPosition[i] = new ImportProcessingService.RowResult(rowNumber,
                    ImportProcessingService.RowStatus.INVALID, rowValuesByPosition.get(i), column,
                    "Column '" + column + "' may have lost precision before this file was created — "
                            + "either the number was too long for Excel to store exactly (~15-16 digits), "
                            + "or it was already collapsed into scientific notation (e.g. \"6.89E+11\") "
                            + "with too few digits to represent the full value.",
                    "Reformat this column as Text in Excel before entering/exporting the number (or "
                            + "prefix the value with an apostrophe), then re-upload with the real values.");
            errors[0]++;
        }

        // Proactive type-check for numeric/boolean columns.
        for (int i = 0; i < chunk.size(); i++) {
            if (state.shouldStop()) {
                return finishChunk(resultsByPosition, inserted, duplicates, errors);
            }
            if (resultsByPosition[i] != null) {
                continue;
            }
            Map<String, Object> rowValues = rowValuesByPosition.get(i);
            for (Map.Entry<String, Object> entry : rowValues.entrySet()) {
                if (entry.getValue() == null) {
                    continue;
                }
                String columnType = ctx.columnTypesLower().get(entry.getKey().toLowerCase(Locale.ROOT));
                String reason = ImportValueNormalizer.describeTypeMismatch(columnType, String.valueOf(entry.getValue()));
                if (reason != null) {
                    if (!reserveInvalidSlot(state)) {
                        return finishChunk(resultsByPosition, inserted, duplicates, errors);
                    }
                    int rowNumber = startingRowNumber + i + 1;
                    resultsByPosition[i] = new ImportProcessingService.RowResult(rowNumber,
                            ImportProcessingService.RowStatus.INVALID, rowValues, entry.getKey(),
                            "Column '" + entry.getKey() + "' " + reason + ", but got '" + entry.getValue() + "'.",
                            "Fix the value in column '" + entry.getKey() + "' and re-upload.");
                    errors[0]++;
                    break;
                }
            }
        }

        // Duplicate-check the whole chunk's still-unresolved rows in one query rather than one per
        // row. Not itself split row-by-row against the stop signal (a single extra query, bounded by
        // CHUNK_SIZE, is a trivial cost next to skipping every later chunk entirely) — but admitting
        // a row found duplicate here still goes through the same reserveInvalidSlot budget check as
        // everything else, and the DB row already-exists check runs before the in-file duplicate
        // check (existingPositions first) matching the original per-row ordering.
        List<Integer> candidatePositions = new ArrayList<>();
        if (!state.shouldStop()) {
            if (ctx.duplicateCheckColumns().isEmpty()) {
                for (int i = 0; i < chunk.size(); i++) {
                    if (resultsByPosition[i] == null) {
                        candidatePositions.add(i);
                    }
                }
            } else {
                List<Map<String, Object>> keyMaps = new ArrayList<>(chunk.size());
                for (Map<String, Object> rowValues : rowValuesByPosition) {
                    Map<String, Object> keyValues = new LinkedHashMap<>();
                    ctx.duplicateCheckColumns().forEach(col -> keyValues.put(col, rowValues.get(col)));
                    keyMaps.add(keyValues);
                }
                Set<Integer> existingPositions = tableAccessService.findExistingRowIndexes(ctx.table(), keyMaps);
                for (int i = 0; i < chunk.size(); i++) {
                    if (resultsByPosition[i] != null) {
                        continue;
                    }
                    if (state.shouldStop()) {
                        break;
                    }
                    int rowNumber = startingRowNumber + i + 1;
                    if (existingPositions.contains(i)) {
                        if (!reserveInvalidSlot(state)) {
                            break;
                        }
                        resultsByPosition[i] = new ImportProcessingService.RowResult(rowNumber,
                                ImportProcessingService.RowStatus.DUPLICATE, rowValuesByPosition.get(i), null, null, null);
                        duplicates[0]++;
                        continue;
                    }
                    // Two rows across the WHOLE upload (not just this chunk) can share a key too —
                    // seenKeysAcrossUpload is shared by every chunk in this run, including concurrent
                    // ones during validation, via an atomic add() (only the first caller for a given
                    // key wins, so a race between two chunks can't let both through).
                    String keyTuple = keyMaps.get(i).entrySet().stream()
                            .map(e -> e.getKey() + "=" + e.getValue())
                            .collect(Collectors.joining("|"));
                    if (!state.seenKeysAcrossUpload().add(keyTuple)) {
                        if (!reserveInvalidSlot(state)) {
                            break;
                        }
                        resultsByPosition[i] = new ImportProcessingService.RowResult(rowNumber,
                                ImportProcessingService.RowStatus.DUPLICATE, rowValuesByPosition.get(i), null, null, null);
                        duplicates[0]++;
                        continue;
                    }
                    candidatePositions.add(i);
                }
            }
        }

        if (!candidatePositions.isEmpty()) {
            DataSource dataSource = jdbcTemplate.getDataSource();
            Connection connection = DataSourceUtils.getConnection(dataSource);
            try {
                List<Map<String, Object>> candidateRows = candidatePositions.stream()
                        .map(insertValuesByPosition::get)
                        .toList();
                List<String> finalInsertColumns = insertColumns;
                List<Map<String, Object>> finalInsertValuesByPosition = insertValuesByPosition;
                if (tryBatchInsert(ctx.table(), finalInsertColumns, candidateRows, connection)) {
                    markAllValid(candidatePositions, rowValuesByPosition, startingRowNumber, resultsByPosition, inserted);
                } else if (candidatePositions.size() == 1) {
                    insertIndividually(ctx.table(), candidatePositions.get(0), rowValuesByPosition,
                            finalInsertValuesByPosition, startingRowNumber, resultsByPosition, inserted, errors, state);
                } else {
                    bisectAndRetry(ctx.table(), finalInsertColumns, candidatePositions, rowValuesByPosition,
                            finalInsertValuesByPosition, startingRowNumber, connection, resultsByPosition, inserted,
                            errors, state);
                }
            } finally {
                DataSourceUtils.releaseConnection(connection, dataSource);
            }
        }

        return finishChunk(resultsByPosition, inserted, duplicates, errors);
    }

    private ImportProcessingService.ChunkOutcome finishChunk(ImportProcessingService.RowResult[] resultsByPosition,
                                                               int[] inserted, int[] duplicates, int[] errors) {
        List<ImportProcessingService.RowResult> results = new ArrayList<>(resultsByPosition.length);
        for (ImportProcessingService.RowResult result : resultsByPosition) {
            if (result != null) {
                results.add(result);
            }
        }
        return new ImportProcessingService.ChunkOutcome(inserted[0], duplicates[0], errors[0], results, false);
    }

    /**
     * Atomically reserves one of the shared {@code state.invalidRowBudget()} invalid-row slots for
     * this run via compare-and-swap — safe under concurrent callers (multiple chunks validating at
     * once). The budget is this table's own tolerance (see {@link TableImportRules#invalidRowBudget}),
     * defaulting to {@link ImportLimits#MAX_INVALID_ROWS}. Returns false once the budget is exhausted,
     * meaning the caller must not mark this row invalid/duplicate at all (leave it unprocessed) rather
     * than admitting one past the limit. The call that fills the very last slot flips the shared stop
     * signal so every other in-flight/future chunk observes it immediately.
     */
    private boolean reserveInvalidSlot(ImportProcessingService.ValidationState state) {
        java.util.concurrent.atomic.AtomicInteger counter = state.invalidRowCount();
        int budget = state.invalidRowBudget();
        int current;
        do {
            current = counter.get();
            if (current >= budget) {
                return false;
            }
        } while (!counter.compareAndSet(current, current + 1));
        if (current + 1 >= budget) {
            state.invalidLimitSignal().set(true);
        }
        return true;
    }

    /**
     * Called only after the whole candidate set has already failed as one batch. Splits it in half
     * and retries each half independently — isolating the actually-bad row(s) instead of falling
     * every row in the original chunk back to one-by-one processing.
     */
    private void bisectAndRetry(String table, List<String> insertColumns, List<Integer> positions,
                                 List<Map<String, Object>> rowValuesByPosition,
                                 List<Map<String, Object>> insertValuesByPosition, int startingRowNumber,
                                 Connection connection, ImportProcessingService.RowResult[] resultsByPosition,
                                 int[] inserted, int[] errors, ImportProcessingService.ValidationState state) {
        int mid = positions.size() / 2;
        attemptBatchOrRecurse(table, insertColumns, positions.subList(0, mid), rowValuesByPosition,
                insertValuesByPosition, startingRowNumber, connection, resultsByPosition, inserted, errors, state);
        attemptBatchOrRecurse(table, insertColumns, positions.subList(mid, positions.size()), rowValuesByPosition,
                insertValuesByPosition, startingRowNumber, connection, resultsByPosition, inserted, errors, state);
    }

    private void attemptBatchOrRecurse(String table, List<String> insertColumns, List<Integer> positions,
                                        List<Map<String, Object>> rowValuesByPosition,
                                        List<Map<String, Object>> insertValuesByPosition, int startingRowNumber,
                                        Connection connection, ImportProcessingService.RowResult[] resultsByPosition,
                                        int[] inserted, int[] errors, ImportProcessingService.ValidationState state) {
        // The single choke point every bisection step passes through — checked here (not just
        // between chunks) because a chunk where most/all candidate rows fail the same way (e.g. an
        // FK violation affecting hundreds of rows at once, such as reference master data not being
        // uploaded yet) recurses all the way down to individual inserts for EVERY row to isolate
        // each failure, which is O(n) extra DB round trips for one bad chunk even though the shared
        // budget only needed the first few of them. Once the budget is exhausted (or the user
        // cancels), every remaining position in flight bails out here instead of issuing another
        // real INSERT attempt — left unprocessed, same as the proactive per-row checks above already
        // do once shouldStop() trips.
        if (state.shouldStop()) {
            return;
        }
        if (positions.size() == 1) {
            insertIndividually(table, positions.get(0), rowValuesByPosition, insertValuesByPosition,
                    startingRowNumber, resultsByPosition, inserted, errors, state);
            return;
        }

        List<Map<String, Object>> rows = positions.stream().map(insertValuesByPosition::get).toList();
        if (tryBatchInsert(table, insertColumns, rows, connection)) {
            markAllValid(positions, rowValuesByPosition, startingRowNumber, resultsByPosition, inserted);
        } else {
            bisectAndRetry(table, insertColumns, positions, rowValuesByPosition, insertValuesByPosition,
                    startingRowNumber, connection, resultsByPosition, inserted, errors, state);
        }
    }

    private void markAllValid(List<Integer> positions, List<Map<String, Object>> rowValuesByPosition,
                               int startingRowNumber, ImportProcessingService.RowResult[] resultsByPosition,
                               int[] inserted) {
        for (int position : positions) {
            int rowNumber = startingRowNumber + position + 1;
            resultsByPosition[position] = new ImportProcessingService.RowResult(rowNumber,
                    ImportProcessingService.RowStatus.VALID, rowValuesByPosition.get(position), null, null, null);
            inserted[0]++;
        }
    }

    /** Isolated single-row insert — same per-row error reporting the pre-bisection fallback used. */
    private void insertIndividually(String table, int position, List<Map<String, Object>> rowValuesByPosition,
                                     List<Map<String, Object>> insertValuesByPosition, int startingRowNumber,
                                     ImportProcessingService.RowResult[] resultsByPosition, int[] inserted,
                                     int[] errors, ImportProcessingService.ValidationState state) {
        int rowNumber = startingRowNumber + position + 1;
        Map<String, Object> rowValues = rowValuesByPosition.get(position);
        try {
            tableAccessService.applyInsert(table, insertValuesByPosition.get(position));
            inserted[0]++;
            resultsByPosition[position] = new ImportProcessingService.RowResult(rowNumber,
                    ImportProcessingService.RowStatus.VALID, rowValues, null, null, null);
        } catch (Exception e) {
            // A DB-level failure discovered only here (not by the proactive checks above, e.g. a
            // NOT NULL violation) still has to go through the same shared budget as everything else —
            // if the budget's already spent, this row is left unrecorded rather than becoming an
            // 11th reported invalid row.
            if (!reserveInvalidSlot(state)) {
                return;
            }
            errors[0]++;
            String rootMessage = ImportValueNormalizer.rootCauseMessage(e);
            resultsByPosition[position] = new ImportProcessingService.RowResult(rowNumber,
                    ImportProcessingService.RowStatus.INVALID, rowValues,
                    resolveErrorColumn(rootMessage), rootMessage,
                    ImportValueNormalizer.suggestSolution(rootMessage));
        }
    }

    /**
     * The column to blame for a failed insert — usually MySQL's "column '...'" wording, but
     * that names the wrong table entirely for a FOREIGN KEY violation (see
     * {@link ImportValueNormalizer#isForeignKeyViolation}): the constraint's own local (child-table)
     * column, resolved live via {@link TableAccessService#getForeignKeyLocalColumns}, is what
     * actually holds the bad value the uploaded row supplied. Falls back to null (no cell
     * highlighted, just the row-level status icon) if that lookup comes up empty for any reason —
     * still correctly flagged INVALID either way, just without a specific cell pinned.
     */
    private String resolveErrorColumn(String rootMessage) {
        if (!ImportValueNormalizer.isForeignKeyViolation(rootMessage)) {
            return ImportValueNormalizer.extractErrorColumn(rootMessage);
        }
        String constraintName = ImportValueNormalizer.extractForeignKeyConstraintName(rootMessage);
        if (constraintName == null) {
            return null;
        }
        List<String> localColumns = tableAccessService.getForeignKeyLocalColumns(constraintName);
        return localColumns.isEmpty() ? null : localColumns.get(0);
    }

    /**
     * Runs one batch INSERT attempt under a fresh savepoint, rolling back to it on failure. A batch
     * either fully succeeds or throws — it never returns normally with some rows silently failed —
     * but the rows executed *before* the failing one are still applied to this open transaction
     * regardless of the exception, so the rollback is what gives the next attempt (a smaller half, or
     * an individual insert) a clean slate instead of re-inserting (and PK-violating on) rows this
     * attempt already partially applied.
     */
    private boolean tryBatchInsert(String table, List<String> effectiveColumns,
                                    List<Map<String, Object>> rows, Connection connection) {
        try {
            Savepoint savepoint = connection.setSavepoint();
            try {
                tableAccessService.applyInsertBatch(table, effectiveColumns, rows);
                return true;
            } catch (Exception batchEx) {
                connection.rollback(savepoint);
                return false;
            }
        } catch (SQLException savepointEx) {
            throw new IllegalStateException("Unable to create a savepoint for batch insert recovery", savepointEx);
        }
    }
}
