package com.houseofbeauty.service.dataupload.import_common;

import com.houseofbeauty.service.common.TableAccessService;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

/**
 * Whole-file, fail-fast check for foreign-key references that don't exist in the table they point at —
 * e.g. a Primary_Sales file whose Bill_to/Ship_to column repeats one unrecognized Site_Code hundreds of
 * times. Run once per {@link ImportProcessingService#run}, before any chunk is validated/inserted: a
 * handful of batched existence queries against the file's DISTINCT values, rather than discovering the
 * same missing value one row at a time via {@link ImportChunkRowProcessor}'s normal per-row insert
 * attempts.
 *
 * <p>Exists specifically so one value missing from a referenced table doesn't burn the shared
 * {@link ImportLimits#MAX_INVALID_ROWS} budget on repeats of the same root cause, hiding every other
 * distinct problem in the file behind identical error rows. When anything is found missing, the caller
 * skips the normal engine entirely for this attempt and reports every DISTINCT missing value instead —
 * capped at {@link ImportLimits#MAX_INVALID_ROWS}, one entry per value (not per occurrence), each noting
 * how many rows in the file it affects.
 */
final class ImportForeignKeyPreCheck {

    private final TableAccessService tableAccessService;

    ImportForeignKeyPreCheck(TableAccessService tableAccessService) {
        this.tableAccessService = tableAccessService;
    }

    List<ImportProcessingService.RowResult> run(String table, List<String> headers,
                                                 Set<String> autoGeneratedColumnsLower, List<List<String>> rows) {
        if (rows.isEmpty()) {
            return List.of();
        }
        List<TableAccessService.ForeignKeyRef> foreignKeys = tableAccessService.getForeignKeyReferences(table);
        if (foreignKeys.isEmpty()) {
            return List.of();
        }

        List<ImportProcessingService.RowResult> missing = new ArrayList<>();
        for (TableAccessService.ForeignKeyRef fk : foreignKeys) {
            missing.addAll(checkOneForeignKey(fk, headers, autoGeneratedColumnsLower, rows));
        }
        missing.sort((a, b) -> Integer.compare(a.rowNumber(), b.rowNumber()));
        return missing;
    }

    private List<ImportProcessingService.RowResult> checkOneForeignKey(TableAccessService.ForeignKeyRef fk,
            List<String> headers, Set<String> autoGeneratedColumnsLower, List<List<String>> rows) {
        List<Integer> columnIndexes = new ArrayList<>();
        for (String localColumn : fk.localColumns()) {
            // A column not present in the file (e.g. an optional Ship_to the upload leaves out
            // entirely) or app-managed rather than taken from the file has nothing to pre-check —
            // left to the database's own handling exactly as before this class existed.
            if (autoGeneratedColumnsLower.contains(localColumn.toLowerCase(Locale.ROOT))) {
                return List.of();
            }
            int idx = indexOfHeaderIgnoreCase(headers, localColumn);
            if (idx < 0) {
                return List.of();
            }
            columnIndexes.add(idx);
        }

        // Distinct, non-null tuples this file actually uses, each remembering its first row number and
        // total occurrence count. A row with a NULL value in any local column (e.g. an optional
        // Ship_to) is skipped here — NULL never violates a FOREIGN KEY, so it's not "missing".
        Map<String, Map<String, Object>> keyValuesByTuple = new LinkedHashMap<>();
        Map<String, Integer> firstRowNumberByTuple = new LinkedHashMap<>();
        Map<String, Integer> occurrenceCountByTuple = new LinkedHashMap<>();

        for (int i = 0; i < rows.size(); i++) {
            List<String> row = rows.get(i);
            Map<String, Object> keyValues = new LinkedHashMap<>();
            boolean anyBlank = false;
            for (int c = 0; c < columnIndexes.size(); c++) {
                int idx = columnIndexes.get(c);
                String value = idx < row.size() ? row.get(idx) : null;
                if (value == null || value.isEmpty()) {
                    anyBlank = true;
                    break;
                }
                keyValues.put(fk.referencedColumns().get(c), value);
            }
            if (anyBlank) {
                continue;
            }
            String tuple = keyValues.entrySet().stream()
                    .map(e -> e.getKey() + "=" + e.getValue())
                    .collect(Collectors.joining("|"));
            keyValuesByTuple.putIfAbsent(tuple, keyValues);
            firstRowNumberByTuple.putIfAbsent(tuple, i + 1);
            occurrenceCountByTuple.merge(tuple, 1, Integer::sum);
        }

        if (keyValuesByTuple.isEmpty()) {
            return List.of();
        }

        List<String> tuples = new ArrayList<>(keyValuesByTuple.keySet());
        List<Map<String, Object>> keyMaps = tuples.stream().map(keyValuesByTuple::get).toList();
        Set<Integer> existingIndexes = tableAccessService.findExistingRowIndexes(fk.referencedTable(), keyMaps);

        String localColumnsLabel = String.join(" + ", fk.localColumns());
        String referencedLabel = fk.referencedTable() + "." + String.join(" + ", fk.referencedColumns());

        List<ImportProcessingService.RowResult> results = new ArrayList<>();
        for (int i = 0; i < tuples.size(); i++) {
            if (existingIndexes.contains(i)) {
                continue;
            }
            String tuple = tuples.get(i);
            Map<String, Object> keyValues = keyValuesByTuple.get(tuple);
            String displayValue = keyValues.values().stream().map(String::valueOf).collect(Collectors.joining(", "));
            int firstRow = firstRowNumberByTuple.get(tuple);
            int occurrences = occurrenceCountByTuple.get(tuple);
            String occurrenceNote = occurrences == 1
                    ? ("only on row " + firstRow)
                    : (occurrences + " rows of this file, first at row " + firstRow);
            String message = "Column '" + localColumnsLabel + "' value '" + displayValue + "' does not exist in "
                    + referencedLabel + " — it appears on " + occurrenceNote + ".";
            String solution = "Add '" + displayValue + "' to " + fk.referencedTable()
                    + " first (or fix the typo if it was meant to match an existing record), then re-upload.";
            results.add(new ImportProcessingService.RowResult(firstRow, ImportProcessingService.RowStatus.INVALID,
                    Map.of(), fk.localColumns().get(0), message, solution));
        }
        return results;
    }

    private static int indexOfHeaderIgnoreCase(List<String> headers, String name) {
        for (int i = 0; i < headers.size(); i++) {
            if (headers.get(i).equalsIgnoreCase(name)) {
                return i;
            }
        }
        return -1;
    }
}
