package com.houseofbeauty.service.dataupload.import_common;

import com.houseofbeauty.service.common.TableAccessService;
import com.houseofbeauty.service.dataupload.tables.ImportBatchMaster;
import com.houseofbeauty.service.dataupload.tables.ImportPrimarySales;
import com.houseofbeauty.service.dataupload.tables.ImportPrimarySalesTarget;
import com.houseofbeauty.service.dataupload.tables.ImportProductMaster;
import com.houseofbeauty.service.dataupload.tables.ImportSecondarySales;
import com.houseofbeauty.service.dataupload.tables.ImportSecondarySalesTarget;
import com.houseofbeauty.service.dataupload.tables.ImportSiteMaster;
import com.houseofbeauty.service.dataupload.tables.ImportStock;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.core.task.TaskExecutor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.PlatformTransactionManager;

import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.Executor;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.function.BooleanSupplier;
import java.util.stream.Collectors;


@Service
public class ImportProcessingService {

    private final TableAccessService tableAccessService;
    private final JdbcTemplate jdbcTemplate;
    private final PlatformTransactionManager transactionManager;
    private final Executor chunkExecutor;
    private final ImportValidationRunner validationRunner;
    private final ImportAtomicCommitRunner commitRunner;
    private final ImportForeignKeyPreCheck foreignKeyPreCheck;

    public ImportProcessingService(TableAccessService tableAccessService, JdbcTemplate jdbcTemplate,
                                    PlatformTransactionManager transactionManager,
                                    @Qualifier("importChunkExecutor") TaskExecutor chunkExecutor) {
        this.tableAccessService = tableAccessService;
        this.jdbcTemplate = jdbcTemplate;
        this.transactionManager = transactionManager;
        this.chunkExecutor = chunkExecutor;

        ImportChunkRowProcessor rowProcessor = new ImportChunkRowProcessor(tableAccessService, jdbcTemplate);
        this.validationRunner = new ImportValidationRunner(tableAccessService, jdbcTemplate, transactionManager,
                chunkExecutor, rowProcessor);
        this.commitRunner = new ImportAtomicCommitRunner(tableAccessService, jdbcTemplate, transactionManager,
                rowProcessor);
        this.foreignKeyPreCheck = new ImportForeignKeyPreCheck(tableAccessService);
    }

    public enum RowStatus { VALID, DUPLICATE, INVALID }

    public record RowResult(int rowNumber, RowStatus status, Map<String, Object> data,
                             String errorColumn, String errorMessage, String solution) {
    }


    public record ImportRunResult(int totalRows, int inserted, int duplicates, int errors,
                                   String transactionStatus, List<String> effectiveHeaders,
                                   List<RowResult> rowResults, boolean cancelled, boolean invalidLimitReached,
                                   String reconciliationStatus, String reconciliationDigest) {
    }


    @FunctionalInterface
    public interface ProgressListener {
        void onProgress(int processedRows, int totalRows, int insertedSoFar, int duplicatesSoFar, int errorsSoFar);
    }


    @FunctionalInterface
    public interface ChunkProgressListener {
        void onChunkUpdate(int chunkIndex, String status, int rowsDone, int rowsTotal);
    }


    @FunctionalInterface
    public interface RowResultListener {
        void onRowResults(List<RowResult> newlyFound);
    }


    record RunContext(String table, List<String> headers, Set<String> autoGeneratedColumns,
                       Set<String> identityColumns, boolean preserveIdentityValues,
                       Set<String> dateColumnsLower, Map<String, String> columnTypesLower,
                       List<String> duplicateCheckColumns, Map<Integer, Set<String>> precisionRiskCells,
                       Map<String, Long> appManagedPkBaseValues, List<String> rowOrderPkColumns) {
    }


    record ValidationState(AtomicInteger invalidRowCount, AtomicBoolean invalidLimitSignal,
                            BooleanSupplier userCancelled, Set<String> seenKeysAcrossUpload, int invalidRowBudget) {
        boolean invalidLimitReached() {
            return invalidLimitSignal.get();
        }

        boolean userCancelledNow() {
            return userCancelled != null && userCancelled.getAsBoolean();
        }

        boolean shouldStop() {
            return invalidLimitSignal.get() || userCancelledNow();
        }
    }

    record ChunkOutcome(int inserted, int duplicates, int errors, List<RowResult> rowResults,
                         boolean criticalFailure) {
    }


    private static final List<TableImportRules> TABLE_RULES = List.of(
            ImportPrimarySales.INSTANCE, ImportPrimarySalesTarget.INSTANCE, ImportBatchMaster.INSTANCE,
            ImportProductMaster.INSTANCE, ImportSiteMaster.INSTANCE, ImportStock.INSTANCE,
            ImportSecondarySales.INSTANCE, ImportSecondarySalesTarget.INSTANCE);


    private static final Set<String> ALWAYS_INSERT_NEW_TABLES = TABLE_RULES.stream()
            .filter(TableImportRules::alwaysInsertNew)
            .map(r -> r.tableKey().toLowerCase(Locale.ROOT))
            .collect(Collectors.toUnmodifiableSet());

    public boolean alwaysAutoGeneratesPrimaryKey(String table) {
        return ALWAYS_INSERT_NEW_TABLES.contains(table.toLowerCase(Locale.ROOT));
    }


    private static final Map<String, Integer> INVALID_ROW_BUDGETS = TABLE_RULES.stream()
            .collect(Collectors.toMap(r -> r.tableKey().toLowerCase(Locale.ROOT), TableImportRules::invalidRowBudget));

    public int invalidRowBudgetFor(String table) {
        return INVALID_ROW_BUDGETS.getOrDefault(table.toLowerCase(Locale.ROOT), ImportLimits.MAX_INVALID_ROWS);
    }

    public ImportRunResult run(String table, List<String> headers, List<List<String>> rows, boolean dryRun,
                                Map<Integer, Set<String>> precisionRiskCells) {
        return run(table, headers, rows, dryRun, precisionRiskCells, null, null, null);
    }

    public ImportRunResult run(String table, List<String> headers, List<List<String>> rows, boolean dryRun,
                                Map<Integer, Set<String>> precisionRiskCells, ProgressListener progressListener) {
        return run(table, headers, rows, dryRun, precisionRiskCells, progressListener, null, null);
    }

    public ImportRunResult run(String table, List<String> headers, List<List<String>> rows, boolean dryRun,
                                Map<Integer, Set<String>> precisionRiskCells, ProgressListener progressListener,
                                BooleanSupplier cancelled) {
        return run(table, headers, rows, dryRun, precisionRiskCells, progressListener, cancelled, null, null);
    }

    public ImportRunResult run(String table, List<String> headers, List<List<String>> rows, boolean dryRun,
                                Map<Integer, Set<String>> precisionRiskCells, ProgressListener progressListener,
                                BooleanSupplier cancelled, ChunkProgressListener chunkProgressListener) {
        return run(table, headers, rows, dryRun, precisionRiskCells, progressListener, cancelled,
                chunkProgressListener, null);
    }

    public ImportRunResult run(String table, List<String> headers, List<List<String>> rows, boolean dryRun,
                                Map<Integer, Set<String>> precisionRiskCells, ProgressListener progressListener,
                                BooleanSupplier cancelled, ChunkProgressListener chunkProgressListener,
                                RowResultListener rowResultListener) {
        return run(table, headers, rows, dryRun, precisionRiskCells, progressListener, cancelled,
                chunkProgressListener, rowResultListener, null);
    }


    public ImportRunResult run(String table, List<String> headers, List<List<String>> rows, boolean dryRun,
                                Map<Integer, Set<String>> precisionRiskCells, ProgressListener progressListener,
                                BooleanSupplier cancelled, ChunkProgressListener chunkProgressListener,
                                RowResultListener rowResultListener, Integer invalidRowBudgetOverride) {
        RunContext ctx = buildRunContext(table, headers, precisionRiskCells);
        List<String> effectiveHeaders = headers.stream()
                .filter(h -> !ctx.autoGeneratedColumns().contains(h.toLowerCase(Locale.ROOT)))
                .toList();


        int invalidRowBudget = invalidRowBudgetOverride != null ? invalidRowBudgetOverride : invalidRowBudgetFor(table);


        List<RowResult> missingReferences = foreignKeyPreCheck.run(table, headers, ctx.autoGeneratedColumns(), rows);
        if (!missingReferences.isEmpty()) {
            return foreignKeyPreCheckFailure(rows.size(), effectiveHeaders, missingReferences, invalidRowBudget);
        }


        ValidationState state = new ValidationState(new AtomicInteger(), new AtomicBoolean(), cancelled,
                ConcurrentHashMap.newKeySet(), invalidRowBudget);

        return dryRun
                ? validationRunner.run(ctx, rows, progressListener, state, effectiveHeaders, chunkProgressListener,
                        rowResultListener)
                : commitRunner.run(ctx, rows, progressListener, state, effectiveHeaders, chunkProgressListener,
                        rowResultListener);
    }


    private ImportRunResult foreignKeyPreCheckFailure(int totalRows, List<String> effectiveHeaders,
                                                        List<RowResult> missingReferences, int invalidRowBudget) {
        List<RowResult> capped = missingReferences.size() > invalidRowBudget
                ? missingReferences.subList(0, invalidRowBudget)
                : missingReferences;
        return new ImportRunResult(totalRows, 0, 0, capped.size(), "Failed", effectiveHeaders, capped, false, true,
                null, null);
    }

    
    private RunContext buildRunContext(String table, List<String> headers,
                                        Map<Integer, Set<String>> precisionRiskCells) {
        List<String> primaryKeyColumns = tableAccessService.getPrimaryKeyColumns(table);
        Set<String> identityColumns = tableAccessService.getIdentityColumns(table);
        Set<String> identityColumnsLower = ImportValueNormalizer.lower(identityColumns);

        Set<String> computedColumnsLower = ImportValueNormalizer.lower(tableAccessService.getComputedColumns(table));
        Set<String> headersLower = ImportValueNormalizer.lower(headers);
        boolean alwaysAutoGenerate = ALWAYS_INSERT_NEW_TABLES.contains(table.toLowerCase(Locale.ROOT));
        Map<String, String> columnTypesOriginalCase = tableAccessService.getColumnTypes(table);
        Map<String, String> columnTypesLower = columnTypesOriginalCase.entrySet().stream()
                .collect(Collectors.toMap(e -> e.getKey().toLowerCase(Locale.ROOT), Map.Entry::getValue));
        Set<String> dateColumnsLower = columnTypesLower.entrySet().stream()
                .filter(e -> DATE_COLUMN_TYPES.contains(e.getValue()))
                .map(Map.Entry::getKey)
                .collect(Collectors.toSet());
        Set<String> autoGeneratedColumns = new HashSet<>(alwaysAutoGenerate
                ? identityColumnsLower
                : identityColumnsLower.stream().filter(c -> !headersLower.contains(c)).collect(Collectors.toSet()));
        autoGeneratedColumns.addAll(computedColumnsLower);
        boolean preserveIdentityValues = !alwaysAutoGenerate
                && identityColumnsLower.stream().anyMatch(headersLower::contains);


        String snColumn = columnTypesOriginalCase.keySet().stream()
                .filter(c -> c.equalsIgnoreCase("SN"))
                .findFirst().orElse(null);
        Map<String, Long> appManagedPkBaseValues = new LinkedHashMap<>();
        if (snColumn != null && !identityColumnsLower.contains(snColumn.toLowerCase(Locale.ROOT))) {
            autoGeneratedColumns.add(snColumn.toLowerCase(Locale.ROOT));
            appManagedPkBaseValues.put(snColumn, tableAccessService.getNextNumericColumnValue(table, snColumn));
        }

        if (alwaysAutoGenerate) {
            for (String column : primaryKeyColumns) {
                if (!identityColumnsLower.contains(column.toLowerCase(Locale.ROOT))
                        && !appManagedPkBaseValues.containsKey(column)) {
                    autoGeneratedColumns.add(column.toLowerCase(Locale.ROOT));
                    appManagedPkBaseValues.put(column, tableAccessService.getNextNumericColumnValue(table, column));
                }
            }
        }


        List<String> duplicateCheckColumns = primaryKeyColumns.stream()
                .filter(c -> !autoGeneratedColumns.contains(c.toLowerCase(Locale.ROOT)))
                .toList();


        List<String> rowOrderPkColumns = List.of();
        if (snColumn == null && !primaryKeyColumns.isEmpty()
                && primaryKeyColumns.stream().noneMatch(c -> autoGeneratedColumns.contains(c.toLowerCase(Locale.ROOT)))) {
            rowOrderPkColumns = primaryKeyColumns;
        }

        return new RunContext(table, headers, autoGeneratedColumns, identityColumns, preserveIdentityValues,
                dateColumnsLower, columnTypesLower, duplicateCheckColumns, precisionRiskCells,
                appManagedPkBaseValues, rowOrderPkColumns);
    }

    private static final Set<String> DATE_COLUMN_TYPES = Set.of("date", "datetime", "timestamp");
}
