package com.houseofbeauty.service.dataupload.import_common;

import com.houseofbeauty.service.common.TableAccessService;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;
import java.util.concurrent.Semaphore;
import java.util.concurrent.atomic.AtomicInteger;


class ImportValidationRunner {

    private final TableAccessService tableAccessService;
    private final JdbcTemplate jdbcTemplate;
    private final PlatformTransactionManager transactionManager;

    private final Executor chunkExecutor;
    private final ImportChunkRowProcessor rowProcessor;

    ImportValidationRunner(TableAccessService tableAccessService, JdbcTemplate jdbcTemplate,
                            PlatformTransactionManager transactionManager, Executor chunkExecutor,
                            ImportChunkRowProcessor rowProcessor) {
        this.tableAccessService = tableAccessService;
        this.jdbcTemplate = jdbcTemplate;
        this.transactionManager = transactionManager;
        this.chunkExecutor = chunkExecutor;
        this.rowProcessor = rowProcessor;
    }

    ImportProcessingService.ImportRunResult run(ImportProcessingService.RunContext ctx, List<List<String>> rows,
                                                 ImportProcessingService.ProgressListener progressListener,
                                                 ImportProcessingService.ValidationState state,
                                                 List<String> effectiveHeaders,
                                                 ImportProcessingService.ChunkProgressListener chunkProgressListener,
                                                 ImportProcessingService.RowResultListener rowResultListener) {
        int totalRows = rows.size();
        List<List<List<String>>> chunks = ImportValueNormalizer.partition(rows, ImportLimits.CHUNK_SIZE);
        boolean simulateIdentityForDryRun = ctx.identityColumns().stream()
                .anyMatch(c -> ctx.autoGeneratedColumns().contains(c.toLowerCase(Locale.ROOT)));


        Semaphore concurrencyGate = new Semaphore(ImportLimits.MAX_PARALLEL_CHUNKS);
        AtomicInteger processedRows = new AtomicInteger();
        AtomicInteger insertedSoFar = new AtomicInteger();
        AtomicInteger duplicatesSoFar = new AtomicInteger();
        AtomicInteger errorsSoFar = new AtomicInteger();


        List<CompletableFuture<ImportProcessingService.ChunkOutcome>> futures = new ArrayList<>(chunks.size());

        int rowNumber = 0;
        int chunkIndex = 0;
        for (List<List<String>> chunk : chunks) {

            if (state.shouldStop()) {
                break;
            }
            int startingRowNumber = rowNumber;
            int chunkSize = chunk.size();
            rowNumber += chunkSize;
            int idx = chunkIndex++;

            acquireUninterruptibly(concurrencyGate);
            if (chunkProgressListener != null) {
                chunkProgressListener.onChunkUpdate(idx, "running", 0, chunkSize);
            }
            CompletableFuture<ImportProcessingService.ChunkOutcome> future = CompletableFuture.supplyAsync(() -> {
                try {
                    if (state.shouldStop()) {
                        return new ImportProcessingService.ChunkOutcome(0, 0, 0, List.of(), false);
                    }
                    return runOneChunkInOwnRolledBackTransaction(ctx, state, chunk, startingRowNumber,
                            simulateIdentityForDryRun);
                } finally {
                    concurrencyGate.release();
                }
            }, chunkExecutor);

            future.thenAccept(outcome -> {
                int processed = processedRows.addAndGet(chunkSize);
                int ins = insertedSoFar.addAndGet(outcome.inserted());
                int dup = duplicatesSoFar.addAndGet(outcome.duplicates());
                int err = errorsSoFar.addAndGet(outcome.errors());
                if (progressListener != null) {
                    progressListener.onProgress(Math.min(processed, totalRows), totalRows, ins, dup, err);
                }
                if (chunkProgressListener != null) {

                    String chunkStatus = outcome.criticalFailure() || outcome.rowResults().size() < chunkSize
                            ? "aborted"
                            : (outcome.errors() > 0 || outcome.duplicates() > 0) ? "flagged" : "passed";
                    chunkProgressListener.onChunkUpdate(idx, chunkStatus, outcome.rowResults().size(), chunkSize);
                }
                if (rowResultListener != null) {
                    List<ImportProcessingService.RowResult> notValid = outcome.rowResults().stream()
                            .filter(r -> r.status() != ImportProcessingService.RowStatus.VALID)
                            .toList();
                    if (!notValid.isEmpty()) {
                        rowResultListener.onRowResults(notValid);
                    }
                }
            });
            futures.add(future);
        }

        CompletableFuture.allOf(futures.toArray(new CompletableFuture[0])).join();

        int inserted = 0;
        int duplicates = 0;
        int errors = 0;
        List<ImportProcessingService.RowResult> rowResults = new ArrayList<>();
        for (CompletableFuture<ImportProcessingService.ChunkOutcome> future : futures) {
            ImportProcessingService.ChunkOutcome outcome = future.join();
            inserted += outcome.inserted();
            duplicates += outcome.duplicates();
            errors += outcome.errors();
            rowResults.addAll(outcome.rowResults());
        }

        boolean invalidLimitReached = state.invalidLimitReached();
        boolean wasCancelled = !invalidLimitReached && state.userCancelledNow();
        String transactionStatus = wasCancelled ? "Cancelled" : "Rolled Back";


        return new ImportProcessingService.ImportRunResult(totalRows, inserted, duplicates, errors, transactionStatus,
                effectiveHeaders, rowResults, wasCancelled, invalidLimitReached, null, null);
    }

    private void acquireUninterruptibly(Semaphore semaphore) {
        boolean acquired = false;
        while (!acquired) {
            try {
                semaphore.acquire();
                acquired = true;
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }
    }

    
    private ImportProcessingService.ChunkOutcome runOneChunkInOwnRolledBackTransaction(
            ImportProcessingService.RunContext ctx, ImportProcessingService.ValidationState state,
            List<List<String>> chunk, int startingRowNumber, boolean simulateIdentityForDryRun) {
        boolean needsIdentityInsert = ctx.preserveIdentityValues() || simulateIdentityForDryRun;
        TransactionTemplate tx = new TransactionTemplate(transactionManager);
        tx.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);

        try {
            return tx.execute(status -> {
                if (needsIdentityInsert) {
                    tableAccessService.setIdentityInsert(ctx.table(), true);
                }
                try {
                    ImportProcessingService.ChunkOutcome outcome = rowProcessor.processChunkCore(ctx, state, chunk,
                            startingRowNumber, simulateIdentityForDryRun);
                    status.setRollbackOnly();
                    return outcome;
                } finally {
                    if (needsIdentityInsert) {
                        tableAccessService.setIdentityInsert(ctx.table(), false);
                    }
                }
            });
        } catch (Exception criticalEx) {

            return systemFailureOutcome(chunk, startingRowNumber, criticalEx);
        }
    }

    private ImportProcessingService.ChunkOutcome systemFailureOutcome(List<List<String>> chunk, int startingRowNumber,
                                                                        Throwable criticalEx) {
        String rootMessage = ImportValueNormalizer.rootCauseMessage(criticalEx);
        List<ImportProcessingService.RowResult> failureResults = new ArrayList<>();
        for (int i = 0; i < chunk.size(); i++) {
            failureResults.add(new ImportProcessingService.RowResult(startingRowNumber + i + 1,
                    ImportProcessingService.RowStatus.INVALID, Map.of(), null,
                    "System failure while processing this batch: " + rootMessage,
                    "This wasn't a data problem — retry the import; if it keeps failing, check the database connection."));
        }
        return new ImportProcessingService.ChunkOutcome(0, 0, chunk.size(), failureResults, true);
    }
}
