package com.houseofbeauty.service.dataupload.import_common;

import com.houseofbeauty.service.common.TableAccessService;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

final class ImportForeignKeyPreCheck {

    private final TableAccessService tableAccessService;

    ImportForeignKeyPreCheck(TableAccessService tableAccessService) {
        this.tableAccessService = tableAccessService;
    }

    List<ImportProcessingService.RowResult> run(String table, List<String> headers,
                                                 Set<String> autoGeneratedColumnsLower, List<List<String>> rows) {
        if (rows.isEmpty()) {
            return List.of();
        }
        List<TableAccessService.ForeignKeyRef> foreignKeys = tableAccessService.getForeignKeyReferences(table);
        if (foreignKeys.isEmpty()) {
            return List.of();
        }

        List<ImportProcessingService.RowResult> missing = new ArrayList<>();
        for (TableAccessService.ForeignKeyRef fk : foreignKeys) {
            missing.addAll(checkOneForeignKey(fk, headers, autoGeneratedColumnsLower, rows));
        }
        missing.sort((a, b) -> Integer.compare(a.rowNumber(), b.rowNumber()));
        return missing;
    }

    private List<ImportProcessingService.RowResult> checkOneForeignKey(TableAccessService.ForeignKeyRef fk,
            List<String> headers, Set<String> autoGeneratedColumnsLower, List<List<String>> rows) {
        List<Integer> columnIndexes = new ArrayList<>();
        for (String localColumn : fk.localColumns()) {

            if (autoGeneratedColumnsLower.contains(localColumn.toLowerCase(Locale.ROOT))) {
                return List.of();
            }
            int idx = indexOfHeaderIgnoreCase(headers, localColumn);
            if (idx < 0) {
                return List.of();
            }
            columnIndexes.add(idx);
        }

        Map<String, Map<String, Object>> keyValuesByTuple = new LinkedHashMap<>();
        Map<String, Integer> firstRowNumberByTuple = new LinkedHashMap<>();
        Map<String, Integer> occurrenceCountByTuple = new LinkedHashMap<>();

        for (int i = 0; i < rows.size(); i++) {
            List<String> row = rows.get(i);
            Map<String, Object> keyValues = new LinkedHashMap<>();
            boolean anyBlank = false;
            for (int c = 0; c < columnIndexes.size(); c++) {
                int idx = columnIndexes.get(c);
                String value = idx < row.size() ? row.get(idx) : null;
                if (value == null || value.isEmpty()) {
                    anyBlank = true;
                    break;
                }
                keyValues.put(fk.referencedColumns().get(c), value);
            }
            if (anyBlank) {
                continue;
            }
            String tuple = keyValues.entrySet().stream()
                    .map(e -> e.getKey() + "=" + e.getValue())
                    .collect(Collectors.joining("|"));
            keyValuesByTuple.putIfAbsent(tuple, keyValues);
            firstRowNumberByTuple.putIfAbsent(tuple, i + 1);
            occurrenceCountByTuple.merge(tuple, 1, Integer::sum);
        }

        if (keyValuesByTuple.isEmpty()) {
            return List.of();
        }

        List<String> tuples = new ArrayList<>(keyValuesByTuple.keySet());
        List<Map<String, Object>> keyMaps = tuples.stream().map(keyValuesByTuple::get).toList();
        Set<Integer> existingIndexes = tableAccessService.findExistingRowIndexes(fk.referencedTable(), keyMaps);

        String localColumnsLabel = String.join(" + ", fk.localColumns());
        String referencedLabel = fk.referencedTable() + "." + String.join(" + ", fk.referencedColumns());

        List<ImportProcessingService.RowResult> results = new ArrayList<>();
        for (int i = 0; i < tuples.size(); i++) {
            if (existingIndexes.contains(i)) {
                continue;
            }
            String tuple = tuples.get(i);
            Map<String, Object> keyValues = keyValuesByTuple.get(tuple);
            String displayValue = keyValues.values().stream().map(String::valueOf).collect(Collectors.joining(", "));
            int firstRow = firstRowNumberByTuple.get(tuple);
            int occurrences = occurrenceCountByTuple.get(tuple);
            String occurrenceNote = occurrences == 1
                    ? ("only on row " + firstRow)
                    : (occurrences + " rows of this file, first at row " + firstRow);
            String message = "Column '" + localColumnsLabel + "' value '" + displayValue + "' does not exist in "
                    + referencedLabel + " — it appears on " + occurrenceNote + ".";
            String solution = "Add '" + displayValue + "' to " + fk.referencedTable()
                    + " first (or fix the typo if it was meant to match an existing record), then re-upload.";
            results.add(new ImportProcessingService.RowResult(firstRow, ImportProcessingService.RowStatus.INVALID,
                    Map.of(), fk.localColumns().get(0), message, solution));
        }
        return results;
    }

    private static int indexOfHeaderIgnoreCase(List<String> headers, String name) {
        for (int i = 0; i < headers.size(); i++) {
            if (headers.get(i).equalsIgnoreCase(name)) {
                return i;
            }
        }
        return -1;
    }
}
