package com.houseofbeauty.service.dataupload.import_common;

import com.houseofbeauty.service.common.TableAccessService;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;
import java.util.concurrent.Semaphore;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Preview (dry run): up to {@link ImportLimits#MAX_PARALLEL_CHUNKS} chunks run concurrently, each
 * attempting its inserts for real inside its own transaction that is <i>always</i> rolled back — so
 * Preview exercises exactly the same INSERT path Commit does (NOT NULL / FK / CHECK / type-conversion
 * validation comes from the database itself, not a hand-written rules engine) without ever touching the
 * database for real. Concurrency is capped by a {@link Semaphore}, not by the injected executor's own
 * pool size — see the constructor.
 */
class ImportValidationRunner {

    private final TableAccessService tableAccessService;
    private final JdbcTemplate jdbcTemplate;
    private final PlatformTransactionManager transactionManager;
    // Dedicated importChunkExecutor bean (see ImportExecutorConfig) — same pool ImportSessionController
    // backgrounds /process jobs on, but separate from Spring Boot's default applicationTaskExecutor
    // that unrelated code also uses. This is just where the work runs; the actual "no more than
    // MAX_PARALLEL_CHUNKS at once" guarantee comes from the Semaphore in run() below.
    private final Executor chunkExecutor;
    private final ImportChunkRowProcessor rowProcessor;

    ImportValidationRunner(TableAccessService tableAccessService, JdbcTemplate jdbcTemplate,
                            PlatformTransactionManager transactionManager, Executor chunkExecutor,
                            ImportChunkRowProcessor rowProcessor) {
        this.tableAccessService = tableAccessService;
        this.jdbcTemplate = jdbcTemplate;
        this.transactionManager = transactionManager;
        this.chunkExecutor = chunkExecutor;
        this.rowProcessor = rowProcessor;
    }

    ImportProcessingService.ImportRunResult run(ImportProcessingService.RunContext ctx, List<List<String>> rows,
                                                 ImportProcessingService.ProgressListener progressListener,
                                                 ImportProcessingService.ValidationState state,
                                                 List<String> effectiveHeaders,
                                                 ImportProcessingService.ChunkProgressListener chunkProgressListener,
                                                 ImportProcessingService.RowResultListener rowResultListener) {
        int totalRows = rows.size();
        List<List<List<String>>> chunks = ImportValueNormalizer.partition(rows, ImportLimits.CHUNK_SIZE);
        boolean simulateIdentityForDryRun = ctx.identityColumns().stream()
                .anyMatch(c -> ctx.autoGeneratedColumns().contains(c.toLowerCase(Locale.ROOT)));

        // Never more than ImportLimits.MAX_PARALLEL_CHUNKS chunks in flight at once — acquired before
        // a chunk is submitted, released when it finishes (success or failure).
        Semaphore concurrencyGate = new Semaphore(ImportLimits.MAX_PARALLEL_CHUNKS);
        AtomicInteger processedRows = new AtomicInteger();
        AtomicInteger insertedSoFar = new AtomicInteger();
        AtomicInteger duplicatesSoFar = new AtomicInteger();
        AtomicInteger errorsSoFar = new AtomicInteger();

        // Submitted in ascending row order; aggregated back in this same list order below (NOT
        // completion order) so the returned rowResults stay row-ordered even though chunks may finish
        // out of order — required for the first-5-plus-10th display, which relies on row order.
        List<CompletableFuture<ImportProcessingService.ChunkOutcome>> futures = new ArrayList<>(chunks.size());

        int rowNumber = 0;
        int chunkIndex = 0;
        for (List<List<String>> chunk : chunks) {
            // Checked before every new chunk — this is what makes "stop immediately at invalid row
            // #10" real rather than cosmetic: once tripped (by this or any other in-flight chunk), no
            // further chunk is ever submitted, so a 1,000,000-row file genuinely stops reading after
            // whichever ~1,000-row chunk contains the 10th invalid row, not after the whole file.
            if (state.shouldStop()) {
                break;
            }
            int startingRowNumber = rowNumber;
            int chunkSize = chunk.size();
            rowNumber += chunkSize;
            int idx = chunkIndex++;

            acquireUninterruptibly(concurrencyGate);
            if (chunkProgressListener != null) {
                chunkProgressListener.onChunkUpdate(idx, "running", 0, chunkSize);
            }
            CompletableFuture<ImportProcessingService.ChunkOutcome> future = CompletableFuture.supplyAsync(() -> {
                try {
                    if (state.shouldStop()) {
                        return new ImportProcessingService.ChunkOutcome(0, 0, 0, List.of(), false);
                    }
                    return runOneChunkInOwnRolledBackTransaction(ctx, state, chunk, startingRowNumber,
                            simulateIdentityForDryRun);
                } finally {
                    concurrencyGate.release();
                }
            }, chunkExecutor);

            future.thenAccept(outcome -> {
                int processed = processedRows.addAndGet(chunkSize);
                int ins = insertedSoFar.addAndGet(outcome.inserted());
                int dup = duplicatesSoFar.addAndGet(outcome.duplicates());
                int err = errorsSoFar.addAndGet(outcome.errors());
                if (progressListener != null) {
                    progressListener.onProgress(Math.min(processed, totalRows), totalRows, ins, dup, err);
                }
                if (chunkProgressListener != null) {
                    // A chunk that didn't finish all of its own rows (rowResults smaller than the
                    // chunk it was given) means the shared invalid-row budget tripped mid-chunk, or —
                    // for a chunk whose turn never even started running — the cap was already tripped
                    // by the time its supplyAsync body executed (see the state.shouldStop() check
                    // above, which returns an empty outcome). Either way that's "aborted", not
                    // "flagged": this chunk was cut off, not merely found to contain bad rows.
                    String chunkStatus = outcome.criticalFailure() || outcome.rowResults().size() < chunkSize
                            ? "aborted"
                            : (outcome.errors() > 0 || outcome.duplicates() > 0) ? "flagged" : "passed";
                    chunkProgressListener.onChunkUpdate(idx, chunkStatus, outcome.rowResults().size(), chunkSize);
                }
                if (rowResultListener != null) {
                    List<ImportProcessingService.RowResult> notValid = outcome.rowResults().stream()
                            .filter(r -> r.status() != ImportProcessingService.RowStatus.VALID)
                            .toList();
                    if (!notValid.isEmpty()) {
                        rowResultListener.onRowResults(notValid);
                    }
                }
            });
            futures.add(future);
        }

        CompletableFuture.allOf(futures.toArray(new CompletableFuture[0])).join();

        int inserted = 0;
        int duplicates = 0;
        int errors = 0;
        List<ImportProcessingService.RowResult> rowResults = new ArrayList<>();
        for (CompletableFuture<ImportProcessingService.ChunkOutcome> future : futures) {
            ImportProcessingService.ChunkOutcome outcome = future.join();
            inserted += outcome.inserted();
            duplicates += outcome.duplicates();
            errors += outcome.errors();
            rowResults.addAll(outcome.rowResults());
        }

        boolean invalidLimitReached = state.invalidLimitReached();
        boolean wasCancelled = !invalidLimitReached && state.userCancelledNow();
        String transactionStatus = wasCancelled ? "Cancelled" : "Rolled Back";

        // No reconciliation for a dry run — every insert here was rolled back, so there's nothing
        // persisted to re-read and re-hash (see ImportCommitReconciler, only ever invoked from
        // ImportAtomicCommitRunner's real commit path).
        return new ImportProcessingService.ImportRunResult(totalRows, inserted, duplicates, errors, transactionStatus,
                effectiveHeaders, rowResults, wasCancelled, invalidLimitReached, null, null);
    }

    private void acquireUninterruptibly(Semaphore semaphore) {
        boolean acquired = false;
        while (!acquired) {
            try {
                semaphore.acquire();
                acquired = true;
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }
        }
    }

    /** One chunk, its own REQUIRES_NEW transaction, always rolled back — see the class javadoc. */
    private ImportProcessingService.ChunkOutcome runOneChunkInOwnRolledBackTransaction(
            ImportProcessingService.RunContext ctx, ImportProcessingService.ValidationState state,
            List<List<String>> chunk, int startingRowNumber, boolean simulateIdentityForDryRun) {
        boolean needsIdentityInsert = ctx.preserveIdentityValues() || simulateIdentityForDryRun;
        TransactionTemplate tx = new TransactionTemplate(transactionManager);
        tx.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);

        try {
            return tx.execute(status -> {
                if (needsIdentityInsert) {
                    tableAccessService.setIdentityInsert(ctx.table(), true);
                }
                try {
                    ImportProcessingService.ChunkOutcome outcome = rowProcessor.processChunkCore(ctx, state, chunk,
                            startingRowNumber, simulateIdentityForDryRun);
                    status.setRollbackOnly();
                    return outcome;
                } finally {
                    if (needsIdentityInsert) {
                        tableAccessService.setIdentityInsert(ctx.table(), false);
                    }
                }
            });
        } catch (Exception criticalEx) {
            // Something escaped the try block above (e.g. a lost DB connection) — Spring has already
            // rolled this chunk back, so none of what was recorded actually happened.
            return systemFailureOutcome(chunk, startingRowNumber, criticalEx);
        }
    }

    private ImportProcessingService.ChunkOutcome systemFailureOutcome(List<List<String>> chunk, int startingRowNumber,
                                                                        Throwable criticalEx) {
        String rootMessage = ImportValueNormalizer.rootCauseMessage(criticalEx);
        List<ImportProcessingService.RowResult> failureResults = new ArrayList<>();
        for (int i = 0; i < chunk.size(); i++) {
            failureResults.add(new ImportProcessingService.RowResult(startingRowNumber + i + 1,
                    ImportProcessingService.RowStatus.INVALID, Map.of(), null,
                    "System failure while processing this batch: " + rootMessage,
                    "This wasn't a data problem — retry the import; if it keeps failing, check the database connection."));
        }
        return new ImportProcessingService.ChunkOutcome(0, 0, chunk.size(), failureResults, true);
    }
}
